server.port=8081
spring.application.name=ms-productos

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/sylvie_db
spring.datasource.username=sylvie_user
spring.datasource.password=sylvie_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=productos
